const products = [
  {
    img: "https://m.media-amazon.com/images/I/316ra22eSTL._AC_SY445_.jpg",
    title: "iPhone 13 Pro Max",
    star: 5,
    reviews: "(1023 reviews)",
    prevPrice: "$1,099.00",
    newPrice: "$999.00",
    company: "Apple",
    color: "Gray",
    category: "phone",
  },
  {
    img: "https://m.media-amazon.com/images/I/71-uDe4TN1L._AC_SL1500_.jpg",
    title: "MacBook Pro 16-inch",
    star: 5,
    reviews: "(789 reviews)",
    prevPrice: "$2,499.00",
    newPrice: "$2,299.00",
    company: "Apple",
    color: "Silver",
    category: "laptop",
  },
  {
    img: "https://m.media-amazon.com/images/I/81WWJj1RedL._AC_SL1500_.jpg",
    title: "iPad Pro 11-inch",
    star: 4,
    reviews: "(532 reviews)",
    prevPrice: "$799.00",
    newPrice: "$749.00",
    company: "Apple",
    color: "Gray",
    category: "tablet",
  },
  {
    img: "https://m.media-amazon.com/images/I/61sRKTAfrhL._AC_SL1500_.jpg",
    title: "AirPods Pro",
    star: 4,
    reviews: "(1234 reviews)",
    prevPrice: "$249.00",
    newPrice: "$199.00",
    company: "Apple",
    color: "White",
    category: "earphone",
  },
  {
    img: "https://m.media-amazon.com/images/I/71aY6fOBaOL._AC_SL1500_.jpg",
    title: "Apple Watch Series 7",
    star: 5,
    reviews: "(852 reviews)",
    prevPrice: "$399.00",
    newPrice: "$349.00",
    company: "Apple",
    color: "Black",
    category: "watch",
  },
  {
    img: "https://m.media-amazon.com/images/I/61O45C5qASL._AC_SL1000_.jpg",
    title: "Samsung Galaxy S21 Ultra",
    star: 5,
    reviews: "(678 reviews)",
    prevPrice: "$1,199.00",
    newPrice: "$1,099.00",
    company: "Samsung",
    color: "Black",
    category: "phone",
  },
  {
    img: "https://m.media-amazon.com/images/I/61d46oYQgdL._AC_SL1500_.jpg",
    title: "Samsung Galaxy Tab S7",
    star: 4,
    reviews: "(456 reviews)",
    prevPrice: "$649.00",
    newPrice: "$599.00",
    company: "Samsung",
    color: "Gray",
    category: "tablet",
  },
  {
    img: "https://m.media-amazon.com/images/I/81ScYVlvRPL._AC_SL1500_.jpg",
    title: "Samsung QLED 4K Smart TV",
    star: 5,
    reviews: "(345 reviews)",
    prevPrice: "$1,299.00",
    newPrice: "$1,099.00",
    company: "Samsung",
    color: "Black",
    category: "tv",
  },
  {
    img: "https://m.media-amazon.com/images/I/610eRpW3dKL._AC_SL1500_.jpg",
    title: "Samsung Galaxy Buds Pro",
    star: 4,
    reviews: "(234 reviews)",
    prevPrice: "$199.00",
    newPrice: "$149.00",
    company: "Samsung",
    color: "Silver",
    category: "earphone",
  },
  {
    img: "https://m.media-amazon.com/images/I/515nMh4oT9S._AC_SL1500_.jpg",
    title: "Microsoft Surface Pro 7",
    star: 4,
    reviews: "(412 reviews)",
    prevPrice: "$899.00",
    newPrice: "$799.00",
    company: "Microsoft",
    color: "Silver",
    category: "laptop",
  },
  {
    img: "https://m.media-amazon.com/images/I/51cN7sQ3aQL._SL1500_.jpg",
    title: "Xbox Series X",
    star: 5,
    reviews: "(1456 reviews)",
    prevPrice: "$499.00",
    newPrice: "$479.00",
    company: "Microsoft",
    color: "White",
    category: "console",
  },
  {
    img: "https://m.media-amazon.com/images/I/6132y3QPcnL._AC_SL1500_.jpg",
    title: "Sony Xperia 1 III",
    star: 4,
    reviews: "(223 reviews)",
    prevPrice: "$1,299.00",
    newPrice: "$1,199.00",
    company: "Sony",
    color: "Black",
    category: "phone",
  },
  {
    img: "https://m.media-amazon.com/images/I/51fM0CKG+HL._SL1500_.jpg",
    title: "PlayStation 5",
    star: 5,
    reviews: "(2314 reviews)",
    prevPrice: "$499.00",
    newPrice: "$499.00",
    company: "Sony",
    color: "White",
    category: "console",
  },
  {
    img: "https://m.media-amazon.com/images/I/41d-Q1ehHdL._AC_SL1500_.jpg",
    title: "Sony WH-1000XM4",
    star: 5,
    reviews: "(1204 reviews)",
    prevPrice: "$349.00",
    newPrice: "$299.00",
    company: "Sony",
    color: "Black",
    category: "earphone",
  },
  {
    img: "https://m.media-amazon.com/images/I/71mJlzZpZDL._AC_SL1500_.jpg",
    title: "Sony Alpha a7 III",
    star: 5,
    reviews: "(987 reviews)",
    prevPrice: "$1,999.00",
    newPrice: "$1,799.00",
    company: "Sony",
    color: "Black",
    category: "camera",
  },
  {
    img: "https://m.media-amazon.com/images/I/51RGPTAnkFL._AC_SL1500_.jpg",
    title: "Google Pixel 6 Pro",
    star: 4,
    reviews: "(654 reviews)",
    prevPrice: "$899.00",
    newPrice: "$849.00",
    company: "Google",
    color: "White",
    category: "phone",
  },
  {
    img: "https://m.media-amazon.com/images/I/61mCvG1PTRL._AC_SL1500_.jpg",
    title: "Google Nest Learning Thermostat",
    star: 5,
    reviews: "(823 reviews)",
    prevPrice: "$249.00",
    newPrice: "$199.00",
    company: "Google",
    color: "White",
    category: "smart home",
  },
  {
    img: "https://m.media-amazon.com/images/I/71G2OoIp9sL._AC_SL1500_.jpg",
    title: "Google Home",
    star: 4,
    reviews: "(512 reviews)",
    prevPrice: "$129.00",
    newPrice: "$99.00",
    company: "Google",
    color: "White",
    category: "smart speaker",
  },
  {
    img: "https://m.media-amazon.com/images/I/81DA7ctdDIL._AC_SL1500_.jpg",
    title: "Sony Alpha a7S III",
    star: 5,
    reviews: "(753 reviews)",
    prevPrice: "$3,499.00",
    newPrice: "$3,199.00",
    company: "Sony",
    color: "Black",
    category: "camera",
  },
  {
    img: "https://m.media-amazon.com/images/I/81SFYXXNQiL._AC_SL1500_.jpg",
    title: "Samsung Galaxy Tab A7",
    star: 4,
    reviews: "(332 reviews)",
    prevPrice: "$229.00",
    newPrice: "$199.00",
    company: "Samsung",
    color: "Gray",
    category: "tablet",
  },
  {
    img: "https://m.media-amazon.com/images/I/41DeT328kPL._AC_SL1000_.jpg",
    title: "MacBook Air M1",
    star: 5,
    reviews: "(945 reviews)",
    prevPrice: "$999.00",
    newPrice: "$899.00",
    company: "Apple",
    color: "Gray",
    category: "laptop",
  },
  {
    img: "https://m.media-amazon.com/images/I/71rP7f78eFL._AC_SL1500_.jpg",
    title: "Apple AirTag",
    star: 4,
    reviews: "(123 reviews)",
    prevPrice: "$29.00",
    newPrice: "$25.00",
    company: "Apple",
    color: "White",
    category: "accessory",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yNmp4OnXS._AC_SL1500_.jpg",
    title: "Samsung Galaxy Watch 4",
    star: 4,
    reviews: "(432 reviews)",
    prevPrice: "$249.00",
    newPrice: "$219.00",
    company: "Samsung",
    color: "Silver",
    category: "watch",
  },
  {
    img: "https://m.media-amazon.com/images/I/61h1v+LwkDL._SL1500_.jpg",
    title: "Xbox Wireless Controller",
    star: 4,
    reviews: "(234 reviews)",
    prevPrice: "$59.00",
    newPrice: "$49.00",
    company: "Microsoft",
    color: "White",
    category: "accessory",
  },
  {
    img: "https://m.media-amazon.com/images/I/71kdXkr974L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "PlayStation 5 Pulse 3D Wireless Headset",
    star: 5,
    reviews: "(765 reviews)",
    prevPrice: "$99.00",
    newPrice: "$89.00",
    company: "Sony",
    color: "Black",
    category: "accessory",
  },
  {
    img: "https://m.media-amazon.com/images/I/517MLzcxhBL._AC_SL1500_.jpg",
    title: "Google Chromecast with Google TV",
    star: 4,
    reviews: "(653 reviews)",
    prevPrice: "$49.00",
    newPrice: "$39.00",
    company: "Google",
    color: "Gray",
    category: "media streaming",
  },
  {
    img: "https://m.media-amazon.com/images/I/61BZ5N9n4IL._AC_SL1500_.jpg",
    title: "Apple Magic Mouse",
    star: 4,
    reviews: "(421 reviews)",
    prevPrice: "$79.00",
    newPrice: "$69.00",
    company: "Apple",
    color: "White",
    category: "accessory",
  },
  {
    img: "https://m.media-amazon.com/images/I/61vs0A5arcL._AC_SL1250_.jpg",
    title: "Sony RX100 VII",
    star: 5,
    reviews: "(332 reviews)",
    prevPrice: "$1,299.00",
    newPrice: "$1,199.00",
    company: "Sony",
    color: "Black",
    category: "camera",
  },
  {
    img: "https://m.media-amazon.com/images/I/51QeS0jkx-L._AC_SL1500_.jpg",
    title: "Microsoft Surface Headphones 2",
    star: 4,
    reviews: "(212 reviews)",
    prevPrice: "$249.00",
    newPrice: "$199.00",
    company: "Microsoft",
    color: "Black",
    category: "earphone",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pcTYT+ICL._AC_SL1500_.jpg",
    title: "Mac Mini M1",
    star: 5,
    reviews: "(652 reviews)",
    prevPrice: "$699.00",
    newPrice: "$599.00",
    company: "Apple",
    color: "Silver",
    category: "pc",
  },
  {
    img: "https://m.media-amazon.com/images/I/71tduSp8ooL._AC_SL1500_.jpg",
    title: "NVIDIA GeForce RTX 3080",
    star: 5,
    reviews: "(981 reviews)",
    prevPrice: "$699.00",
    newPrice: "$649.00",
    company: "NVIDIA",
    color: "Black",
    category: "pc component",
  },
  {
    img: "https://m.media-amazon.com/images/I/81xrbB98D7L._AC_SY445_.jpg",
    title: "Samsung Galaxy Note 20 Ultra",
    star: 5,
    reviews: "(753 reviews)",
    prevPrice: "$1,299.00",
    newPrice: "$1,199.00",
    company: "Samsung",
    color: "Black",
    category: "phone",
  },
  {
    img: "https://m.media-amazon.com/images/I/71XySfAlGuL._AC_SL1500_.jpg",
    title: "Google Pixelbook Go",
    star: 4,
    reviews: "(542 reviews)",
    prevPrice: "$849.00",
    newPrice: "$749.00",
    company: "Google",
    color: "Black",
    category: "laptop",
  },
  {
    img: "https://m.media-amazon.com/images/I/7122bjHMoFL._AC_SL1500_.jpg",
    title: "Apple Watch SE",
    star: 4,
    reviews: "(762 reviews)",
    prevPrice: "$279.00",
    newPrice: "$249.00",
    company: "Apple",
    color: "Silver",
    category: "watch",
  },
  {
    img: "https://m.media-amazon.com/images/I/71LUq9OEmPL._AC_SL1500_.jpg",
    title: "Sony X95J 4K TV",
    star: 5,
    reviews: "(763 reviews)",
    prevPrice: "$2,199.00",
    newPrice: "$1,999.00",
    company: "Sony",
    color: "Black",
    category: "tv",
  },
  {
    img: "https://m.media-amazon.com/images/I/81sX1nwD+fL._AC_SL1500_.jpg",
    title: "Razer Blade 15",
    star: 5,
    reviews: "(674 reviews)",
    prevPrice: "$2,299.00",
    newPrice: "$2,099.00",
    company: "Razer",
    color: "Black",
    category: "laptop",
  },
  {
    img: "https://m.media-amazon.com/images/I/51HgkLHvLoL._AC_SY550_.jpg",
    title: "Alienware Aurora R12",
    star: 5,
    reviews: "(556 reviews)",
    prevPrice: "$1,999.00",
    newPrice: "$1,799.00",
    company: "Dell",
    color: "Silver",
    category: "pc",
  },
  {
    img: "https://m.media-amazon.com/images/I/61+403-rNoL._AC_SL1500_.jpg",
    title: "Logitech MX Keys",
    star: 4,
    reviews: "(344 reviews)",
    prevPrice: "$99.00",
    newPrice: "$89.00",
    company: "Logitech",
    color: "Black",
    category: "accessory",
  },
  {
    img: "https://m.media-amazon.com/images/I/61Ufzi3lugL._AC_SL1440_.jpg",
    title: "Razer Kraken Tournament Edition",
    star: 4,
    reviews: "(293 reviews)",
    prevPrice: "$79.00",
    newPrice: "$69.00",
    company: "Razer",
    color: "Green",
    category: "earphone",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Ir4cW5GNL._AC_SL1500_.jpg",
    title: "Dell XPS 13",
    star: 5,
    reviews: "(845 reviews)",
    prevPrice: "$1,199.00",
    newPrice: "$1,099.00",
    company: "Dell",
    color: "Silver",
    category: "laptop",
  },
];

const colorCount = products.reduce((acc, product) => {
  acc[product.color] = (acc[product.color] || 0) + 1;
  return acc;
}, {});

console.log(colorCount);
